"""
Generator for rFactor .veh (vehicle) files.

Generates vehicle configuration files from Vehicle objects.
"""

from pathlib import Path
from typing import Optional

from ..models.vehicle import Vehicle


class VehGenerator:
    """Generator for .veh vehicle files."""

    def generate_content(self, vehicle: Vehicle) -> str:
        """
        Generate the content of a .veh file from a Vehicle object.

        Args:
            vehicle: Vehicle object to generate from

        Returns:
            String content for the .veh file
        """
        lines = []

        # Header comment
        lines.append("// rFactor Vehicle Configuration")
        lines.append("// Generated by rFactor Championship Creator")
        lines.append("")

        # Vehicle basic info
        if vehicle.description:
            lines.append(f'Description="{vehicle.description}"')

        if vehicle.number is not None:
            lines.append(f"Number={vehicle.number}")

        if vehicle.category:
            lines.append(f'Category="{vehicle.category}"')

        if vehicle.classes:
            lines.append(f'Classes="{vehicle.classes}"')

        if vehicle.manufacturer:
            lines.append(f'Manufacturer="{vehicle.manufacturer}"')

        if vehicle.engine:
            lines.append(f'Engine="{vehicle.engine}"')

        lines.append("")

        # Team info
        if vehicle.team_info:
            if vehicle.team_info.driver:
                lines.append(f'Driver="{vehicle.team_info.driver}"')

            if vehicle.team_info.team:
                lines.append(f'Team="{vehicle.team_info.team}"')

            if vehicle.team_info.full_team_name:
                lines.append(f'FullTeamName="{vehicle.team_info.full_team_name}"')

            if vehicle.team_info.pit_group:
                lines.append(f'PitGroup="{vehicle.team_info.pit_group}"')

            if vehicle.team_info.team_founded is not None:
                lines.append(f"TeamFounded={vehicle.team_info.team_founded}")

            if vehicle.team_info.team_headquarters:
                lines.append(f'TeamHeadquarters="{vehicle.team_info.team_headquarters}"')

            if vehicle.team_info.team_starts is not None:
                lines.append(f"TeamStarts={vehicle.team_info.team_starts}")

            if vehicle.team_info.team_poles is not None:
                lines.append(f"TeamPoles={vehicle.team_info.team_poles}")

            if vehicle.team_info.team_wins is not None:
                lines.append(f"TeamWins={vehicle.team_info.team_wins}")

            if vehicle.team_info.team_world_championships is not None:
                lines.append(f"TeamWorldChampionships={vehicle.team_info.team_world_championships}")

        lines.append("")

        # Configuration
        if vehicle.config:
            if vehicle.config.default_livery:
                lines.append(f'DefaultLivery="{vehicle.config.default_livery}"')

            if vehicle.config.hdvehicle:
                lines.append(f'HDVehicle="{vehicle.config.hdvehicle}"')

            if vehicle.config.gen_string:
                lines.append(f'GenString="{vehicle.config.gen_string}"')

            if vehicle.config.graphics:
                lines.append(f'Graphics="{vehicle.config.graphics}"')

            if vehicle.config.spinner:
                lines.append(f'Spinner="{vehicle.config.spinner}"')

            if vehicle.config.upgrades:
                lines.append(f'Upgrades="{vehicle.config.upgrades}"')

            if vehicle.config.sounds:
                lines.append(f'Sounds="{vehicle.config.sounds}"')

            if vehicle.config.cameras:
                lines.append(f'Cameras="{vehicle.config.cameras}"')

            if vehicle.config.head_physics:
                lines.append(f'HeadPhysics="{vehicle.config.head_physics}"')

            if vehicle.config.cockpit:
                lines.append(f'Cockpit="{vehicle.config.cockpit}"')

            if vehicle.config.ai_upgrade_class:
                lines.append(f'AIUpgradeClass="{vehicle.config.ai_upgrade_class}"')

        lines.append("")

        return '\n'.join(lines)

    def write_file(self, vehicle: Vehicle, file_path: str | Path) -> None:
        """
        Write a .veh file from a Vehicle object.

        Args:
            vehicle: Vehicle object to write
            file_path: Path where to write the file
        """
        file_path = Path(file_path)

        # Create parent directories if they don't exist
        file_path.parent.mkdir(parents=True, exist_ok=True)

        # Generate content
        content = self.generate_content(vehicle)

        # Write file with Windows-1252 encoding (standard for rFactor files)
        with open(file_path, 'w', encoding='windows-1252') as f:
            f.write(content)
